# Generated by Django 3.0.7 on 2020-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200717_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='addresse',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
    ]
